POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: "application/json"

{
    "title": "My first blog",
    "author": "This is my first blog.. lorem ipsum text...",
    "url":"https://localhost:3003/api/blogs/1",
    "likes": 99
}

###
POST http://localhost:3003/api/blogs
Content-Type: "application/json"

{
    "title": "My first blog from restful api"
}
###
GET http://127.0.0.1:3003/api/blogs HTTP/1.1