DELETE http://localhost:3001/api/persons/64dcb458a54d46a2b180ecaf
###
GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/64dcb458a54d46a2b180ecaf

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name":"Test Person",
   "number":"009779854"
}